---
title: "My Dataset"
output: "github_document"
date: "2024-09-26"
---
```{r}
# Set a CRAN mirror
options(repos = c(CRAN = "https://cran.rstudio.com/"))

```

```{r}
#install.packages("dplyr")
library(car)
library(dplyr) #recode variables
library(tidyr)
library(ggplot2)
#library(psych)
#library(bruceR)
library(haven) #load CSV

#install.packages("nortest")

#ibrary(nortest)
#install.packages("car")
```
Reading dataset 
```{r}
# Set working directory
#setwd("C:/Users/sidne/OneDrive/Documents/GitHub/myproject")

# Read the TSV file
data <- read.table("C:/Users/sidne/OneDrive/Desktop/PSY329/38964-0001-Data.tsv", sep = "\t", header = TRUE, fill = TRUE, quote = "")

# Write the data to a CSV file
write.csv(data, "Excel-Data.csv", row.names = FALSE)

#open file
data <- read.csv("C:/Users/sidne/OneDrive/Desktop/PSY329/Excel-Data.csv")

```

Cleaning data set and recoding variables
```{r}
clean_data <- data %>%
  select(SEX,HHINC,HAPPY,SAT1,SAT2,SAT3,SAT4,SAT5,LONELY_A,LONELY_B,LONELY_C) 

clean_data$SEX<-recode(data$SEX, '1' = 'Male', '2' = 'Female', '3'='Other')

clean_data$HOUSE_INCOME<-recode(data$HHINC, '1' = 'Low', '2' = 'Low', '3'='Low','4'='Low','5'='Low','6'='Middle','7'='Middle','8'='Middle','9'='Middle','10'='Middle','11'='High','12'='High')

clean_data$HAPPY_meaning<-recode(data$HAPPY, '1' = 'Very happy', '2' = 'Rather happy', '3'='Not very happy','4'='Not at all happy')

clean_data <- clean_data %>%
   mutate(Lonely=rowMeans(cbind(LONELY_A,LONELY_B,LONELY_C))) #1 hardly ever feel lonely to 5 often feel lonely 

clean_data <- clean_data %>%
  mutate(Lonely = ifelse(Lonely > 3, NA, Lonely)) #removing participants that responded don't know or refused the question

clean_data <- clean_data %>%
   mutate(Life_satisfaction=rowMeans(cbind(SAT1,SAT2,SAT3,SAT4,SAT5))) #1 strongly disagree to 5 strongly agree higher score = higher life satisfaction

clean_data <- clean_data %>%
  mutate(Life_satisfaction = ifelse(Life_satisfaction > 5, NA, Life_satisfaction))

clean_data$HAPPY_REV <- 5 - clean_data$HAPPY #reverse code happy so higher number = happier

clean_data <- clean_data %>%
  select(SEX,HOUSE_INCOME,HAPPY_meaning, HAPPY_REV,Life_satisfaction, SAT1,SAT2,SAT3,SAT4,SAT5,Lonely, LONELY_A,LONELY_B,LONELY_C)

clean_data<- drop_na(clean_data)


write.csv(clean_data, "C:/Users/sidne/OneDrive/Desktop/PSY329/clean_data.csv", row.names = FALSE)

```

Normality of Lonely
```{r}

ggplot(clean_data, aes(x = Lonely)) + geom_histogram(binwidth = 0.5) + facet_wrap(~SEX)+theme_classic() #between SEX

ggplot(clean_data, aes(x = Lonely)) + geom_histogram(binwidth = 0.5) + facet_wrap(~HOUSE_INCOME)+theme_classic() #between INCOME

clean_data %>%
  group_by(SEX) %>% 
  summarize(W = shapiro.test(Lonely)$statistic, p_value = shapiro.test(Lonely)$p.value)

clean_data %>%
  group_by(HOUSE_INCOME) %>% 
  summarize(W = shapiro.test(Lonely)$statistic, p_value = shapiro.test(Lonely)$p.value)
```

Normality of Life satisfaction
```{r}
ggplot(clean_data, aes(x = Life_satisfaction)) + geom_histogram(binwidth = 0.5) + facet_wrap(~SEX)+theme_classic()

ggplot(clean_data, aes(x = Life_satisfaction)) + geom_histogram(binwidth = 0.5) + facet_wrap(~HOUSE_INCOME)+theme_classic()

clean_data %>%
  group_by(SEX) %>% 
  summarize(W = shapiro.test(Life_satisfaction)$statistic, p_value = shapiro.test(Life_satisfaction)$p.value)

clean_data %>%
  group_by(HOUSE_INCOME) %>% 
  summarize(W = shapiro.test(Life_satisfaction)$statistic, p_value = shapiro.test(Life_satisfaction)$p.value)
```

Normality of Happiness
```{r}
ggplot(clean_data, aes(x = HAPPY_REV)) + geom_histogram(binwidth = 1) + facet_wrap(~SEX)+theme_classic()

ggplot(clean_data, aes(x = HAPPY_REV)) + geom_histogram(binwidth = 1) + facet_wrap(~HOUSE_INCOME)+theme_classic()

clean_data %>%
  group_by(SEX) %>% 
  summarize(W = shapiro.test(HAPPY_REV)$statistic, p_value = shapiro.test(HAPPY_REV)$p.value)

clean_data %>%
  group_by(HOUSE_INCOME) %>% 
  summarize(W = shapiro.test(HAPPY_REV)$statistic, p_value = shapiro.test(HAPPY_REV)$p.value)

```
Variance of Lonely
```{r}
clean_data %>%
  group_by(SEX) %>%
  summarize(variacne = var(Lonely))

leveneTest(Lonely~SEX, clean_data)

clean_data %>%
  group_by(HOUSE_INCOME) %>%
  summarize(variacne = var(Lonely))

leveneTest(Lonely~HOUSE_INCOME, clean_data)
```
Variance of Life satisfaction
```{r}
clean_data %>%
  group_by(SEX) %>%
  summarize(variacne = var(Life_satisfaction))

leveneTest(Life_satisfaction~SEX, clean_data)

clean_data %>%
  group_by(HOUSE_INCOME) %>%
  summarize(variacne = var(Life_satisfaction))

leveneTest(Life_satisfaction~HOUSE_INCOME, clean_data)

```
Variance of Happiness
```{r}
clean_data %>%
  group_by(SEX) %>%
  summarize(variacne = var(HAPPY_REV))

leveneTest(HAPPY_REV~SEX, clean_data)

clean_data %>%
  group_by(HAPPY_REV) %>%
  summarize(variacne = var(Life_satisfaction))

leveneTest(HAPPY_REV~HOUSE_INCOME, clean_data)
```
Data transformations
```{r}
clean_data$Lonely_log <- sqrt(clean_data$Lonely)

clean_data$HappyREV_log <- sqrt(clean_data$HAPPY_REV)

clean_data$Lifesat_log <- sqrt(clean_data$Life_satisfaction)
```

Normality of Lonely_Log
```{r}

ggplot(clean_data, aes(x = Lonely_log)) + geom_histogram(binwidth = 0.5) + facet_wrap(~SEX)+theme_classic() #between SEX

ggplot(clean_data, aes(x = Lonely_log)) + geom_histogram(binwidth = 0.5) + facet_wrap(~HOUSE_INCOME)+theme_classic() #between INCOME

clean_data %>%
  group_by(SEX) %>% 
  summarize(W = shapiro.test(Lonely_log)$statistic, p_value = shapiro.test(Lonely_log)$p.value)

clean_data %>%
  group_by(HOUSE_INCOME) %>% 
  summarize(W = shapiro.test(Lonely_log)$statistic, p_value = shapiro.test(Lonely_log)$p.value)
```

Normality of Lifesat_Log
```{r}

ggplot(clean_data, aes(x = Lifesat_log)) + geom_histogram(binwidth = 0.5) + facet_wrap(~SEX)+theme_classic() #between SEX

ggplot(clean_data, aes(x = Lifesat_log)) + geom_histogram(binwidth = 0.5) + facet_wrap(~HOUSE_INCOME)+theme_classic() #between INCOME

clean_data %>%
  group_by(SEX) %>% 
  summarize(W = shapiro.test(Lifesat_log)$statistic, p_value = shapiro.test(Lifesat_log)$p.value)

clean_data %>%
  group_by(HOUSE_INCOME) %>% 
  summarize(W = shapiro.test(Lifesat_log)$statistic, p_value = shapiro.test(Lifesat_log)$p.value)
```
Normality of Happrev_log
```{r}

ggplot(clean_data, aes(x = HappyREV_log)) + geom_histogram(binwidth = 0.5) + facet_wrap(~SEX)+theme_classic() #between SEX

ggplot(clean_data, aes(x = HappyREV_log)) + geom_histogram(binwidth = 0.5) + facet_wrap(~HOUSE_INCOME)+theme_classic() #between INCOME

clean_data %>%
  group_by(SEX) %>% 
  summarize(W = shapiro.test(HappyREV_log)$statistic, p_value = shapiro.test(Lifesat_log)$p.value)

clean_data %>%
  group_by(HOUSE_INCOME) %>% 
  summarize(W = shapiro.test(HappyREV_log)$statistic, p_value = shapiro.test(Lifesat_log)$p.value)
```
